// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    PageLoading: typeof import('./../components/PageLoading.vue')['default']
    UserCenter: typeof import('./../components/UserCenter.vue')['default']
  }
}

export { }
